name: wandroid_flutter
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #国际化
  flutter_localizations:
    sdk: flutter
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  #框架：https://pub.dev/packages/fish_redux#-installing-tab-
  fish_redux: ^0.3.4

  #网络:https://github.com/flutterchina/dio/blob/flutter/README-ZH.md
  dio: ^3.0.10

  #网络状态监听:https://pub.dev/packages/connectivity#-installing-tab-
  connectivity: ^0.4.9

  #国际化：https://pub.dev/packages/flutter_i18n#-installing-tab-
  flutter_i18n: ^0.19.1

  #序列化:https://pub.dartlang.org/packages/json_serializable#-readme-tab-
  json_serializable: ^3.4.0

  #网络图片:https://pub.dev/packages/cached_network_image#-installing-tab-
  cached_network_image: ^2.2.0+1

  #网络请求动画:https://pub.dev/packages/flutter_spinkit
  flutter_spinkit: "^3.1.0"

  #视频:https://pub.dev/packages/video_player#-installing-tab-
  video_player: 0.7.2

  #刷新:https://github.com/xuelongqy/flutter_easyrefresh
  flutter_easyrefresh: ^1.2.7

  #webview:https://pub.dartlang.org/packages/flutter_webview_plugin#-installing-tab-
  flutter_webview_plugin: ^0.3.0+2

  #banner:https://github.com/best-flutter/flutter_swiper/blob/master/README-ZH.md
  flutter_swiper: ^1.1.6

  #数据库:https://pub.dev/packages/sqflite#-readme-tab-
  sqflite: ^1.1.0

  #sp:https://pub.dev/packages/shared_preferences#-installing-tab-
  shared_preferences: ^0.5.8

  #工具类:https://pub.dev/packages/common_utils#-installing-tab-
  common_utils: ^1.2.1

  #toast:https://github.com/PonnamKarthik/FlutterToast
  fluttertoast: ^7.0.2

  #适配:https://github.com/OpenFlutter/flutter_screenutil/blob/master/README_CN.md
  flutter_screenutil: ^2.3.0

  nima: ^1.0.0
  flare_flutter: ^1.4.0

dev_dependencies:


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - resources/images/sh_img.jpg
    - resources/images/my_flutter_logo_false.png
    - resources/images/my_flutter_logo_true.png
    - resources/images/huo_false.png
    - resources/images/huo_true.png
    - resources/images/android.png
    - resources/images/aixing.png
    - resources/images/defult_bac_img.png
    - resources/images/flutter_logo.png
    - resources/images/no_select_cir.png
    - resources/images/select_cir.png
    - resources/video/start_page_video.mp4
    - resources/video/guide_one.mp4
    - resources/video/guide_two.mp4
    - resources/video/guide_thread.mp4
    - resources/animations/Big Green Guy.nima
    - resources/animations/Big Green Guy.png
    - resources/animations/low_poly_wolf.flr
    - resources/animations/Teddy.flr
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
